node {
   
   properties([
    parameters([
    choice(name: 'TARGET_ENV', choices: ['DEV', 'HOM', 'PRD'], description: 'Target environment'),
    ])
   ])
   
   stage('Environment') {
      env.MAVEN_HOME = tool 'M3'
      env.JAVA_HOME = tool 'IIB JDK'
      env.MQSI_BASE_FILEPATH = "C:\\Program Files\\IBM\\IIB\\10.0.0.15"
      env.PATH = "$MAVEN_HOME\\bin;$MQSI_BASE_FILEPATH;$MQSI_BASE_FILEPATH\\tools;$MQSI_BASE_FILEPATH\\server\\bin;$PATH";
   }

   def COMPONENT_NAME = "iib-maven-plugin-poc"
   def COMPONENT_BASE_DIR = "${WORKSPACE}\\${COMPONENT_NAME}"
   
   stage('Git') {
      cleanWs()
      git 'https://github.com/rfontans/iib-projects.git'   
      fileOperations([folderDeleteOperation(folderPath: '.git'), fileDeleteOperation(includes: '*')])
   }

   /*
   def LOCAL_REPO = "C:\\Users\\rfontans\\Documents\\GitHub\\iib-projects"
   stage('LocalRepo') {
      fileOperations([
         folderCopyOperation(sourceFolderPath: "${LOCAL_REPO}\\${COMPONENT_NAME}", destinationFolderPath: "${COMPONENT_BASE_DIR}")
      ])
   }
   */
   
   def POM_ARTIFACT_ID
   def POM_VERSION

   stage('Build') {
      def POM_FILE = "${COMPONENT_BASE_DIR}\\pom.xml"
      def pom = readMavenPom file: POM_FILE
      POM_ARTIFACT_ID = pom.artifactId
      POM_VERSION = pom.version
      bat(/mvn -f ${POM_FILE} -Dmaven.test.failure.ignore clean package/)
   }
   
   stage('Archive'){
       archiveArtifacts artifacts: "${COMPONENT_NAME}\\target\\iib\\*.bar", onlyIfSuccessful: true
   }
   
   stage('Deploy') {
       def IIB_NODE = 'TESTNODE_rfontans'
       bat(/mqsiprofile && mqsideploy ${IIB_NODE} -e default -a ${COMPONENT_BASE_DIR}\target\iib\${TARGET_ENV}_${POM_VERSION}.bar -w 120 -v deploy-trace.log/)
       bat(/mqsiprofile && mqsistopmsgflow ${IIB_NODE} -e default -w 30 -f restartExecutionGroup/)
       bat(/mqsiprofile && mqsilist ${IIB_NODE}/)
   }
}